#! /bin/bash
# Generates a png from a file containing just a latex equation expression
# author: mcncm 2019 

ENTROPY=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 10)
FILENAME="${1##*/}"
FILENAME_NO_EXT="${FILENAME%.*}"
FILENAME_MANGLED="$FILENAME_NO_EXT"_"$ENTROPY"

cat > $FILENAME_MANGLED.tex << EOM
\\documentclass[preview]{standalone}
\\usepackage{amsmath}
\\usepackage{amssymb}
\\usepackage{xcolor}
\\begin{document}
\\nopagecolor
\\begin{align*}
$(cat $1)
\\end{align*}
\\end{document}
EOM

echo Made LaTeX document...

pdflatex $FILENAME_MANGLED.tex > /dev/null 2>&1
echo Made pdf document...

convert -quiet -density 800 $FILENAME_MANGLED.pdf -quality 100 -depth 8 -flatten -transparent white -fuzz 1% -trim $FILENAME_NO_EXT.png
echo Made png...

rm $FILENAME_MANGLED.*
echo Cleaned up.

